# .github/workflows/scrape.yml (クリーン版)
name: Amazon Rank Scraper

on:
  schedule:
    - cron: '0 * * * *' # 毎時0分に実行
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのコードをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonのセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: PythonライブラリとPlaywrightブラウザのインストール
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir --upgrade gspread beautifulsoup4 pandas playwright playwright-stealth
          python -m playwright install --with-deps

      - name: スクレイピング実行
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python main.py
